[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#e0f2fe"
secondaryBackgroundColor = "#bae6fd"
textColor = "#0c4a6e"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false